In [5]:
# Importing important libraries
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [6]:
# from google.colab import drive
# drive.mount('/content/drive')

# Reading the CSV file with Pandas

In [7]:
df = pd.read_csv("C:/Users/MSI GF63/Desktop/ImageClassification/patient-characteristics-survey-pcs-2017-1.csv",  skipinitialspace=True)

In [8]:
df.shape

(187192, 67)

In [9]:
df.isnull().sum().sum()

0

In [10]:
print(df.head())

   Survey Year Program Category         Region Served Age Group     Sex  \
0         2017       OUTPATIENT     CENTRAL NY REGION     ADULT  FEMALE   
1         2017          SUPPORT        WESTERN REGION     ADULT  FEMALE   
2         2017       OUTPATIENT     CENTRAL NY REGION     ADULT  FEMALE   
3         2017       OUTPATIENT  NEW YORK CITY REGION     ADULT  FEMALE   
4         2017       OUTPATIENT     CENTRAL NY REGION     ADULT    MALE   

           Transgender        Sexual Orientation       Hispanic Ethnicity  \
0  NO, NOT TRANSGENDER  STRAIGHT OR HETEROSEXUAL  NO, NOT HISPANIC/LATINO   
1  NO, NOT TRANSGENDER                   UNKNOWN  NO, NOT HISPANIC/LATINO   
2  NO, NOT TRANSGENDER  STRAIGHT OR HETEROSEXUAL  NO, NOT HISPANIC/LATINO   
3  NO, NOT TRANSGENDER  STRAIGHT OR HETEROSEXUAL  NO, NOT HISPANIC/LATINO   
4  NO, NOT TRANSGENDER  STRAIGHT OR HETEROSEXUAL  NO, NOT HISPANIC/LATINO   

         Race   Living Situation  ... Unknown Insurance Coverage No Insurance  \
0  WH

In [11]:
# Removing the null values
df.dropna(how = 'any')

# Remove Unknown data from the dataframe
for column in df.columns:
    df = df[(df[column] != 'UNKNOWN')]

In [12]:
# Encoding the data to numberical to better calculation

le = preprocessing.LabelEncoder()

for column in df.columns:
    df[column] = le.fit_transform(df[column])

In [13]:
print(df)

        Survey Year  Program Category  Region Served  Age Group  Sex  \
2                 0                 2              0          0    0   
4                 0                 2              0          0    1   
7                 0                 2              3          0    0   
8                 0                 2              0          0    0   
10                0                 2              4          0    1   
...             ...               ...            ...        ...  ...   
187184            0                 3              3          0    0   
187186            0                 2              2          0    0   
187187            0                 3              4          0    1   
187190            0                 3              3          0    0   
187191            0                 2              0          1    0   

        Transgender  Sexual Orientation  Hispanic Ethnicity  Race  \
2                 1                   4                   0     4 

In [14]:
# Spliting the data into features and label

X = df.loc[:, df.columns != 'Stroke']
Y = df.loc[:, ['Stroke']].values.ravel()

In [15]:
len(X.columns)

66

In [16]:
features = df.loc[:, ['No Chronic Med Condition','Age Group','Living Situation','Other Insurance','Endocrine Condition','Other Chronic Med Condition','Obesity','Special Education Services','Sex','Child Health Plus Insurance','Medicaid Managed Insurance','Autism Spectrum', 'Private Insurance', 'Medicare Insurance', 'Heart Attack', 'Transgender', 'Liver Disease', 'Drug Substance Disorder', 'Criminal Justice Status']]
label = Y

In [17]:
len(features.columns)

19

In [18]:
print(features)

        No Chronic Med Condition  Age Group  Living Situation  \
2                              0          0                 2   
4                              1          0                 2   
7                              0          0                 2   
8                              0          0                 2   
10                             0          0                 1   
...                          ...        ...               ...   
187184                         0          0                 2   
187186                         0          0                 1   
187187                         0          0                 1   
187190                         0          0                 1   
187191                         1          1                 2   

        Other Insurance  Endocrine Condition  Other Chronic Med Condition  \
2                     0                    0                            0   
4                     0                    0                     

In [19]:
print(label)

[0 0 0 ... 0 0 0]


In [20]:
from sklearn import svm
# Selecting the appropriate model by checking their accuracy

models=[]
models.append(("KNN",KNeighborsClassifier()))
models.append(("Support vector Machine",SVC()))
models.append(("GaussianNB",GaussianNB()))
models.append(("Decesion",DecisionTreeClassifier()))

In [21]:
# Setting up the parameters for kFold

kv=KFold(n_splits=10, random_state=8, shuffle=True)

In [22]:
# Checking the accuracy for each listed above model

for names,model in models:
    results=cross_val_score(model,features,label,cv=kv,scoring="accuracy")
    print(names,results.mean(),"\n")

C:\conda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\conda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid thi

KNN 0.9844315733699389 

Support vector Machine 0.9850351088748045 

GaussianNB 0.4409453243518919 

Decesion 0.983642327263105 



In [23]:
#Gaussian Naive Bayes 

# Split features and label in train and test
X_train, X_test, Y_train, Y_test = train_test_split(features, label, test_size=0.5, random_state=0)

# Call GaussianNB object
gnb = GaussianNB()

# Train the model
gnb.fit(X_train, Y_train)

# Predict the test data
Y_pred = gnb.predict(X_test)
print(Y_pred)

[1 1 1 ... 1 1 0]


In [24]:
# Print the Accuracy score

print("Accuracy:", metrics.accuracy_score(Y_test, Y_pred) * 100, '%')

Accuracy: 43.28205763100065 %


In [25]:
#KNN

# Split features and label in train and test
X_train, X_test, Y_train, Y_test = train_test_split(features, label, test_size=0.5, random_state=0)

# Call GaussianNB object
knn = KNeighborsClassifier()

# Train the model
knn.fit(X_train, Y_train)

# Predict the test data
Y_pred = knn.predict(X_test)
print(Y_pred)

C:\conda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


[0 0 0 ... 0 0 0]


In [26]:
# Print the Accuracy score

print("Accuracy:", metrics.accuracy_score(Y_test, Y_pred) * 100, '%')

Accuracy: 98.56696276579281 %


In [27]:
#SVM

# Split features and label in train and test
X_train, X_test, Y_train, Y_test = train_test_split(features, label, test_size=0.5, random_state=0)

# Call GaussianNB object
SVM = SVC()

# Train the model
SVM.fit(X_train, Y_train)

# Predict the test data
Y_pred = SVM.predict(X_test)
print(Y_pred)

[0 0 0 ... 0 0 0]


In [28]:
# Print the Accuracy score

print("Accuracy:", metrics.accuracy_score(Y_test, Y_pred) * 100, '%')

Accuracy: 98.62267479649634 %


##Traning accuracy:0.9850351088748045 
## Testing accuracy: 98.62267479649634 %

In [29]:
#Decision 

# Split features and label in train and test
X_train, X_test, Y_train, Y_test = train_test_split(features, label, test_size=0.5, random_state=0)

# Call GaussianNB object
decisiontree = DecisionTreeClassifier()

# Train the model
decisiontree.fit(X_train, Y_train)

# Predict the test data
Y_pred = decisiontree.predict(X_test)
print(Y_pred)

[0 0 0 ... 0 0 0]


In [30]:
# Print the Accuracy score

print("Accuracy:", metrics.accuracy_score(Y_test, Y_pred) * 100, '%')

Accuracy: 98.38125599678108 %


## Training accuracy: 0.9655823903734767 
## Testing accuracy: 96.44371537342536 %

In [31]:
# ROC Curve

fpr, tpr, thresholds = metrics.roc_curve(Y_test, Y_pred)
print("False Positive Rate", fpr)
print("True Positive Rate", tpr)
print("Threshold", thresholds)

False Positive Rate [0.         0.00279312 1.        ]
True Positive Rate [0.        0.0247191 1.       ]
Threshold [2 1 0]


In [32]:
# Logarithmic Loss

log_loss = metrics.log_loss(Y_test, Y_pred)
print("Logarithmic Loss: ", log_loss)

Logarithmic Loss:  0.559096574289195


In [33]:
# print the Classification Report

class_report = classification_report(Y_test,Y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99     31864
           1       0.11      0.02      0.04       445

    accuracy                           0.98     32309
   macro avg       0.55      0.51      0.52     32309
weighted avg       0.97      0.98      0.98     32309



In [34]:
# Print Confusin Matrix

conf_mat=confusion_matrix(Y_test,Y_pred)
print(conf_mat)

[[31775    89]
 [  434    11]]


In [35]:
print("donee")

donee


In [36]:
# save the model
import pickle
filename='predstroke.pkl'
pickle.dump(SVM,open(filename,'wb'))

In [37]:
load_model=pickle.load(open(filename,'rb'))

In [47]:
res=load_model.predict([[1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]])
res


C:\conda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])

In [43]:
X_train.iloc[1]

No Chronic Med Condition       1
Age Group                      0
Living Situation               2
Other Insurance                0
Endocrine Condition            0
Other Chronic Med Condition    0
Obesity                        0
Special Education Services     1
Sex                            1
Child Health Plus Insurance    0
Medicaid Managed Insurance     2
Autism Spectrum                0
Private Insurance              0
Medicare Insurance             0
Heart Attack                   0
Transgender                    1
Liver Disease                  0
Drug Substance Disorder        0
Criminal Justice Status        0
Name: 121417, dtype: int32

In [39]:
if res[0]==1:
    print("you risk to have a stroke in the future")
else:
    print("you are fine future hamdoulah")

you are fine future hamdoulah
